{
 "title": "Cosmos-Validator_exporter",
 "description": "This exporter is for monitoring information which is not provided from Tendermint’s basic Prometheus exporter (localhost:26660), and other specific information monitoring purposes",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "label": "select the datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Story Node Dashboard",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "options": {
    "content": "<img src=\"https://files.readme.io/50fccae-small-Storywhite.png\"/>"
   },
   "targets": [
    {
     "expr": "Cosmos_labels{instance=\"192.168.1.64:26660\"}\t",
     "legendFormat": "{{chainId}}"
    }
   ]
  },
  {
   "title": "[ Current Block Time ]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "cometbft_consensus_block_interval_seconds_sum{chain_id=\"iliad-0\"}/cometbft_consensus_block_interval_seconds_count{chain_id=\"iliad-0\"}",
     "legendFormat": "currentBlockTime"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_height{chain_id=\"iliad-0\",instance=\"192.168.1.64:26660\"}",
     "legendFormat": "BlockHeight"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lib_buildinfo_version{version=\"v0.9.12\"}",
     "legendFormat": "LibraryVersion"
    }
   ]
  },
  {
   "title": "[ Block Interval Times ]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(cometbft_consensus_block_interval_seconds_bucket{chain_id=\"iliad-0\"}[5m])) by (le))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_validators_power{chain_id=\"iliad-0\"}\n",
     "legendFormat": "Validator Stake"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_validators{chain_id=\"iliad-0\"}",
     "legendFormat": "Validator Count"
    }
   ]
  },
  {
   "title": "Transaction Success Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 9, "y": 7 },
   "targets": [
    {
     "expr": "sum(rate(cosmos_tx_count[5m])) ",
     "legendFormat": "Transaction"
    },
    {
     "expr": "sum(rate(cosmos_tx_successful [5m])) ",
     "legendFormat": "Success"
    }
   ]
  },
  {
   "title": "[ Sync Status ]",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_blocksync_syncing{chain_id=\"iliad-0\"}",
     "legendFormat": "jailStatus"
    }
   ]
  },
  {
   "title": "[ Token Info ]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "cosmos_minted_tokens{module=\"mint\"} ",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "[ABCI Method Timing]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(cometbft_abci_connection_method_timing_seconds_bucket{chain_id=\"iliad-0\"}[5m])) by (le, method))\n",
     "legendFormat": "{{Method}}"
    }
   ]
  }
 ]
}